version: '3'
services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: mariadb
      MARIADB_URL: db
      MARIADB_USER: root
      MARIADB_PASSWORD: secret
  db:
    image: mariadb
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: assignment